name: Deploy Discord Bot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Upgrade pip y configurar índice de paquetes
        run: |
          python -m pip install --upgrade pip
          pip config set global.index-url https://pypi.org/simple
      
      - name: Instalar dependencias
        run: |
          pip install aiohttp==3.11.11
          pip install -r requirements.txt
      
      - name: Run the bot
        run: |
          python prueba2.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

